### ISSUE TITLE
Update on the status of this gem

### ISSUE THREAD

**Issue by iancanderson** [iancanderson/ingreedy#19]
@balvig @firewalker06 @tapster - Didn't know how else to reach you, but I wanted to say thanks for the work you've done on this gem, and apologize for not being more responsive to the PRs. @balvig - as of today I brought in the latest commits from your master branch into upstream master. FYI I rebased the changes on top of mine, so you might want to re-create your fork to make clear diffs for future PRs.

The latest gem version, 0.0.7 has the latest changes brought in from @balvig's fork.

I would like to better maintain the gem going forward, and would appreciate your help for future releases!

**Comment by iancanderson** [comment]
Closing since this was just a hack to ping all of you :smile:

**Comment by tapster** [comment]
Great! Thanks! :+1:

**Comment by firewalker06** [comment]
A pleasure to help :+1:

**Comment by balvig** [comment]
@iancanderson awesome! Was wondering what had become of you :sweat_smile: 
Thanks again for sharing to begin with, has been a big help :+1:
