### ISSUE TITLE
Dictionary missing from gem?

### ISSUE THREAD

**Issue by andyw8** [iancanderson/ingreedy#24]
When I try to use the gem in a project, it fails with:

"2.2.0/gems/ingreedy-0.0.7/lib/ingreedy/dictionary_collection.rb:32:in `rescue in load_yaml': No dictionary found for :en locale (RuntimeError)"

I download the gem file and extracted it, and it does seem to be missing the `lib/ingreedy/dictionaries` directory, I guess it's because the `gemspec` is set to use `Dir.glob("lib/**/*.rb")` so misses the YAML.

**Comment by iancanderson** [comment]
Thanks @andyw8! - fixed in gem version 0.0.8
