### ISSUE TITLE
please, push to github

### ISSUE THREAD

**Issue by matkoniecz** [iancanderson/ingreedy#35]
according to https://rubygems.org/gems/ingreedy 0.1.0 was released at August 19, 2016

https://github.com/iancanderson/ingreedy/blob/master/lib/ingreedy/version.rb has at this moment version 0.0.9 with latest update at 26 Jan 2016

Can you consider pushing to github so it at least matches version available as a gem?

**Comment by photostu** [comment]
+1

**Comment by matkoniecz** [comment]
I send an email to ian@iancanderson.com (found at http://iancanderson.com/)

**Comment by iancanderson** [comment]
Pushed the latest version to master, sorry for the wait!
