### ISSUE TITLE
should differentiate ingredients extra text... im talking about adding NLP

### ISSUE THREAD

**Issue by vjaykoogu** [iancanderson/ingreedy#5]
Its works great but also should remove extra texts.

ex:  Ingredients list.
------------------------------------------------------------------------------
    2 ounces thick-cut bacon (about 3 slices), small dice
    1 medium yellow onion, small dice
    3 cups fresh or frozen corn kernels (thaw if frozen)
    3 cups whole milk
    1 pound russet potatoes (about 2 medium), peeled and medium dice
    2 teaspoons kosher salt, plus more as needed
    1/2 teaspoon freshly ground black pepper, plus more as needed
    1/2 cup heavy cream
    Finely chopped chives, for serving

* This should give result like this
-------------------------------------------------------------
 result.amount   #=> 2
result.unit    #=> :ounces
result.ingredient   #=> "bacon "
result.text #=>  thick-cut small dice

ex 2
---------------------------------------------------
 result.amount   #=> 1
result.unit    #=> :medium
result.ingredient   #=> " yellow onion"
result.text #=>   small dice

**Comment by iancanderson** [comment]
thanks for the suggestion, but I don't see a way to implement this without machine learning and a big data set backing the algorithm, which is outside of the scope of what I want this gem to do.
